# Generated by Django 5.2.9 on 2025-12-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('tier', models.IntegerField()),
                ('emoji', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
