# Generated by Django 5.2.9 on 2025-12-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='emoji',
            field=models.CharField(max_length=11),
        ),
    ]
